id: I56509E85
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:22:37+00:00'
last_modified: '2022-06-08T09:24:32.818944+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD1100
  title: གཏེར་ཆོས། རིག་འཛིན་ཉི་མ་གྲགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6195':
      image_group_id: I4PD487
      title: ''
      total_pages: 502
      order: 1
      base_file: 6195.txt
    D06B:
      image_group_id: I4PD488
      title: ''
      total_pages: 322
      order: 2
      base_file: D06B.txt
    BB42:
      image_group_id: I4PD489
      title: ''
      total_pages: 562
      order: 3
      base_file: BB42.txt
    '6541':
      image_group_id: I4PD490
      title: ''
      total_pages: 822
      order: 4
      base_file: 6541.txt
    A3CA:
      image_group_id: I4PD491
      title: ''
      total_pages: 550
      order: 5
      base_file: A3CA.txt
    47A6:
      image_group_id: I4PD492
      title: ''
      total_pages: 562
      order: 6
      base_file: 47A6.txt
    EA93:
      image_group_id: I4PD493
      title: ''
      total_pages: 648
      order: 7
      base_file: EA93.txt
    094E:
      image_group_id: I4PD494
      title: ''
      total_pages: 662
      order: 8
      base_file: 094E.txt
    23A2:
      image_group_id: I4PD495
      title: ''
      total_pages: 662
      order: 9
      base_file: 23A2.txt
    F626:
      image_group_id: I4PD496
      title: ''
      total_pages: 396
      order: 10
      base_file: F626.txt
    35C7:
      image_group_id: I4PD497
      title: ''
      total_pages: 500
      order: 11
      base_file: 35C7.txt
    '0575':
      image_group_id: I4PD498
      title: ''
      total_pages: 620
      order: 12
      base_file: 0575.txt
    0A48:
      image_group_id: I4PD499
      title: ''
      total_pages: 746
      order: 13
      base_file: 0A48.txt
    '6644':
      image_group_id: I4PD500
      title: ''
      total_pages: 756
      order: 14
      base_file: 6644.txt
    CC0F:
      image_group_id: I4PD501
      title: ''
      total_pages: 580
      order: 15
      base_file: CC0F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
