id: I56509E85
legacy_id: P009211
ocr_import_info:
  bdrc_scan_id: W3PD1100
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T04:17:18'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T17:21:00.189290+00:00'
last_modified: 2022-09-04 01:25:29.909944
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3PD1100
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3PD1100
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཏེར་ཆོས། རིག་འཛིན་ཉི་མ་གྲགས་པ།
  author: རིག་འཛིན་ཉི་མ་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9056591019863909
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I4PD495:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD495
      total_pages: 662
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I4PD495.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9315068414413246
    legacy_id: v009
  I4PD494:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD494
      total_pages: 662
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4PD494.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9332474745105138
    legacy_id: v008
  I4PD489:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD489
      total_pages: 562
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4PD489.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9430443762125459
    legacy_id: v003
  I4PD498:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD498
      total_pages: 620
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I4PD498.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9245803289067227
    legacy_id: v012
  I4PD492:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD492
      total_pages: 562
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4PD492.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.7867620591378438
    legacy_id: v006
  I4PD499:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD499
      total_pages: 746
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I4PD499.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9187599205031537
    legacy_id: v013
  I4PD487:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD487
      total_pages: 502
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD487.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.963155614872618
    legacy_id: v001
  I4PD501:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD501
      total_pages: 580
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I4PD501.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9594870273600685
    legacy_id: v015
  I4PD490:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD490
      total_pages: 822
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4PD490.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.810135042394819
    legacy_id: v004
  I4PD488:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD488
      total_pages: 322
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD488.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.922440932264288
    legacy_id: v002
  I4PD491:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD491
      total_pages: 550
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4PD491.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9088727592728288
    legacy_id: v005
  I4PD500:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD500
      total_pages: 756
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I4PD500.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9316446518369776
    legacy_id: v014
  I4PD497:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD497
      total_pages: 500
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I4PD497.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9324231042958885
    legacy_id: v011
  I4PD493:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD493
      total_pages: 648
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4PD493.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8677469164453365
    legacy_id: v007
  I4PD496:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD496
      total_pages: 396
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I4PD496.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9107570144915832
    legacy_id: v010
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
