id: P009211
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD1100
  title: གཏེར་ཆོས། རིག་འཛིན་ཉི་མ་གྲགས་པ།
  author: ''
  volumes:
    ab6ea721f2834d55b2b1a28be155ef41:
      image_group_id: I4PD487
      title: ''
      volume_number: 1
      total_pages: 502
    613276c7524d4d62babb032dfcd23a44:
      image_group_id: I4PD488
      title: ''
      volume_number: 2
      total_pages: 322
    b40fcfdcd2344ce98795c03fff159396:
      image_group_id: I4PD489
      title: ''
      volume_number: 3
      total_pages: 562
    cb91105a442b4e728285a78f4fd21816:
      image_group_id: I4PD490
      title: ''
      volume_number: 4
      total_pages: 822
    7a561cdf27774e87ac5ed2e295c2d9eb:
      image_group_id: I4PD491
      title: ''
      volume_number: 5
      total_pages: 550
    681af6e7f8f140bd971f8c0017d316ab:
      image_group_id: I4PD492
      title: ''
      volume_number: 6
      total_pages: 562
    1b68d8afbed8446cb99aad3ca0b1e0f5:
      image_group_id: I4PD493
      title: ''
      volume_number: 7
      total_pages: 648
    b7c15dcf4ecf404eaa31600e5a4c1df1:
      image_group_id: I4PD494
      title: ''
      volume_number: 8
      total_pages: 662
    6e2efc7bb32e415997d0ce03bbdb3669:
      image_group_id: I4PD495
      title: ''
      volume_number: 9
      total_pages: 662
    69a1164b1b844fd293801f9822170ee3:
      image_group_id: I4PD496
      title: ''
      volume_number: 10
      total_pages: 396
    39ae75678d774618884cc9aa0f4f2c7a:
      image_group_id: I4PD497
      title: ''
      volume_number: 11
      total_pages: 500
    42f45f9538b54afd96c5636ac902e7b8:
      image_group_id: I4PD498
      title: ''
      volume_number: 12
      total_pages: 620
    6d20fafa5f31460681a98ccf9a609b96:
      image_group_id: I4PD499
      title: ''
      volume_number: 13
      total_pages: 746
    cebf8deba80d49a4a4b8711b50058288:
      image_group_id: I4PD500
      title: ''
      volume_number: 14
      total_pages: 756
    0744058beab044af8f1583459888345c:
      image_group_id: I4PD501
      title: ''
      volume_number: 15
      total_pages: 580
