id: P009211
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:28:15.064492
source_metadata:
  id: bdr:W3PD1100
  title: གཏེར་ཆོས། རིག་འཛིན་ཉི་མ་གྲགས་པ།
  author: ''
  volumes:
    ab6ea721f2834d55b2b1a28be155ef41:
      image_group_id: I4PD487
      title: ''
      volume_number: 1
      total_pages: 502
      base_file: v001.txt
    613276c7524d4d62babb032dfcd23a44:
      image_group_id: I4PD488
      title: ''
      volume_number: 2
      total_pages: 322
      base_file: v002.txt
    b40fcfdcd2344ce98795c03fff159396:
      image_group_id: I4PD489
      title: ''
      volume_number: 3
      total_pages: 562
      base_file: v003.txt
    cb91105a442b4e728285a78f4fd21816:
      image_group_id: I4PD490
      title: ''
      volume_number: 4
      total_pages: 822
      base_file: v004.txt
    7a561cdf27774e87ac5ed2e295c2d9eb:
      image_group_id: I4PD491
      title: ''
      volume_number: 5
      total_pages: 550
      base_file: v005.txt
    681af6e7f8f140bd971f8c0017d316ab:
      image_group_id: I4PD492
      title: ''
      volume_number: 6
      total_pages: 562
      base_file: v006.txt
    1b68d8afbed8446cb99aad3ca0b1e0f5:
      image_group_id: I4PD493
      title: ''
      volume_number: 7
      total_pages: 648
      base_file: v007.txt
    b7c15dcf4ecf404eaa31600e5a4c1df1:
      image_group_id: I4PD494
      title: ''
      volume_number: 8
      total_pages: 662
      base_file: v008.txt
    6e2efc7bb32e415997d0ce03bbdb3669:
      image_group_id: I4PD495
      title: ''
      volume_number: 9
      total_pages: 662
      base_file: v009.txt
    69a1164b1b844fd293801f9822170ee3:
      image_group_id: I4PD496
      title: ''
      volume_number: 10
      total_pages: 396
      base_file: v010.txt
    39ae75678d774618884cc9aa0f4f2c7a:
      image_group_id: I4PD497
      title: ''
      volume_number: 11
      total_pages: 500
      base_file: v011.txt
    42f45f9538b54afd96c5636ac902e7b8:
      image_group_id: I4PD498
      title: ''
      volume_number: 12
      total_pages: 620
      base_file: v012.txt
    6d20fafa5f31460681a98ccf9a609b96:
      image_group_id: I4PD499
      title: ''
      volume_number: 13
      total_pages: 746
      base_file: v013.txt
    cebf8deba80d49a4a4b8711b50058288:
      image_group_id: I4PD500
      title: ''
      volume_number: 14
      total_pages: 756
      base_file: v014.txt
    0744058beab044af8f1583459888345c:
      image_group_id: I4PD501
      title: ''
      volume_number: 15
      total_pages: 580
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
